import type { WidgetId, CollapseSide } from '../types';

export interface WidgetDef {
  id: WidgetId;
  title: string;
  shortTitle: string;          // for collapsed rail labels
  icon: string;                // lucide icon name
  defaultCollapseSide: CollapseSide;
  minW: number;
  minH: number;
  expandable: boolean;         // supports full-expand overlay
  collapsible: boolean;        // can be sent to rail
}

export const WIDGET_REGISTRY: Record<WidgetId, WidgetDef> = {
  'status-summary': {
    id: 'status-summary',
    title: 'Market Status',
    shortTitle: 'Status',
    icon: 'Activity',
    defaultCollapseSide: 'left',
    minW: 4,
    minH: 2,
    expandable: false,
    collapsible: true,
  },
  'kpi-slippage': {
    id: 'kpi-slippage',
    title: 'Slippage Cost Impact',
    shortTitle: 'Slippage',
    icon: 'TrendingDown',
    defaultCollapseSide: 'left',
    minW: 2,
    minH: 3,
    expandable: false,
    collapsible: true,
  },
  'kpi-spread': {
    id: 'kpi-spread',
    title: 'Spread Delta',
    shortTitle: 'Spread',
    icon: 'ArrowLeftRight',
    defaultCollapseSide: 'left',
    minW: 2,
    minH: 3,
    expandable: false,
    collapsible: true,
  },
  'kpi-latency': {
    id: 'kpi-latency',
    title: 'Latency',
    shortTitle: 'Latency',
    icon: 'Clock',
    defaultCollapseSide: 'right',
    minW: 2,
    minH: 3,
    expandable: false,
    collapsible: true,
  },
  'kpi-routing-risk': {
    id: 'kpi-routing-risk',
    title: 'Routing Risk',
    shortTitle: 'Risk',
    icon: 'Shield',
    defaultCollapseSide: 'right',
    minW: 2,
    minH: 3,
    expandable: false,
    collapsible: true,
  },
  'execution-simulator': {
    id: 'execution-simulator',
    title: 'Execution Simulator',
    shortTitle: 'Simulator',
    icon: 'Route',
    defaultCollapseSide: 'left',
    minW: 6,
    minH: 4,
    expandable: true,
    collapsible: true,
  },
  'market-health': {
    id: 'market-health',
    title: 'Market Health',
    shortTitle: 'Health',
    icon: 'Radio',
    defaultCollapseSide: 'right',
    minW: 4,
    minH: 4,
    expandable: true,
    collapsible: true,
  },
  'chart-spread': {
    id: 'chart-spread',
    title: 'Spread Alignment',
    shortTitle: 'Spread Chart',
    icon: 'BarChart3',
    defaultCollapseSide: 'left',
    minW: 4,
    minH: 4,
    expandable: true,
    collapsible: true,
  },
  'chart-slippage': {
    id: 'chart-slippage',
    title: 'Slippage Trajectory',
    shortTitle: 'Slip Chart',
    icon: 'LineChart',
    defaultCollapseSide: 'left',
    minW: 4,
    minH: 4,
    expandable: true,
    collapsible: true,
  },
  'table-liquidity': {
    id: 'table-liquidity',
    title: 'Liquidity Profile',
    shortTitle: 'Profile',
    icon: 'Table2',
    defaultCollapseSide: 'right',
    minW: 4,
    minH: 4,
    expandable: true,
    collapsible: true,
  },
  'orderbook-tm': {
    id: 'orderbook-tm',
    title: 'True Markets Book',
    shortTitle: 'TM Book',
    icon: 'BookOpen',
    defaultCollapseSide: 'right',
    minW: 2,
    minH: 3,
    expandable: true,
    collapsible: true,
  },
  'orderbook-bench': {
    id: 'orderbook-bench',
    title: 'Benchmark Book',
    shortTitle: 'Bench Book',
    icon: 'BookOpen',
    defaultCollapseSide: 'right',
    minW: 2,
    minH: 3,
    expandable: true,
    collapsible: true,
  },
  'alert-center': {
    id: 'alert-center',
    title: 'Alert Center',
    shortTitle: 'Alerts',
    icon: 'Bell',
    defaultCollapseSide: 'right',
    minW: 2,
    minH: 3,
    expandable: false,
    collapsible: true,
  },
};

/** Ordered list of widget IDs for default rendering */
export const DEFAULT_WIDGET_ORDER: WidgetId[] = [
  'status-summary',
  'kpi-slippage',
  'kpi-spread',
  'kpi-latency',
  'kpi-routing-risk',
  'execution-simulator',
  'market-health',
  'chart-spread',
  'chart-slippage',
  'table-liquidity',
  'orderbook-tm',
  'orderbook-bench',
];
