using FluentAssertions;
using TradingEngineServer.Core.Models;
using TradingEngineServer.Core.Services;

namespace TradingEngineServer.Tests;

public class ReplayEngineTests
{
    private const string Symbol = "BTCUSD";

    [Fact]
    public void Replay_Should_Rebuild_Expected_State()
    {
        // Arrange
        var orderBook = new OrderBook(Symbol);
        var replayEngine = new ReplayEngine();

        // Let's create a simulated event log:
        // 1. NewOrder (Buy 2 @ 68000)
        // 2. NewOrder (Buy 3 @ 67500)
        // 3. NewOrder (Sell 1 @ 67500)  <-- Crosses Buy 2
        // 4. TradeExecution (1 @ 67500) <-- Generated by match
        // 5. CancelOrder (Buy 2 @ 68000) <-- Cancel the first order
        var events = new List<EngineEvent>
        {
            EngineEvent.NewOrder(0, new OrderCore(1, 68000m, 2, true, "Alice")),
            EngineEvent.NewOrder(1, new OrderCore(2, 67500m, 3, true, "Bob")),
            EngineEvent.NewOrder(2, new OrderCore(3, 67500m, 1, false, "Charlie")),
            EngineEvent.TradeExecution(3, 67500m, 1, 2, 3), // Derivation event, should be ignored by replay engine
            EngineEvent.CancelOrder(4, 1)
        };

        // Act
        var result = replayEngine.Replay(events, orderBook);

        // Assert
        result.EventsReplayed.Should().Be(5);
        result.NewOrdersReplayed.Should().Be(3);
        result.CancelsReplayed.Should().Be(1);
        result.TradesGenerated.Should().Be(1); // The matching engine should generate exactly 1 trade

        var snapshot = result.FinalSnapshot;
        snapshot.Should().NotBeNull();
        snapshot!.Bids.Should().HaveCount(1); // Only Bob's bid is left
        snapshot.Asks.Should().HaveCount(0); // Charlie's sell was fully filled

        // Bob's bid was 3, Charlie's sell of 1 matched Alice's higher bid of 2.
        // Then Alice's remaining 1 was cancelled. Leaving exactly Bob's 3.
        snapshot.Bids[0].Price.Should().Be(67500m);
        snapshot.Bids[0].Size.Should().Be(3);
    }
}
