// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_EXECUTIONCOACH_SIM_H_
#define FLATBUFFERS_GENERATED_SCHEMA_EXECUTIONCOACH_SIM_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace ExecutionCoach {
namespace Sim {

struct Quote;
struct QuoteBuilder;

struct SimulationRequest;
struct SimulationRequestBuilder;

enum ExecutionMode : int8_t {
  ExecutionMode_ExecuteNow = 0,
  ExecutionMode_Slice = 1,
  ExecutionMode_Defensive = 2,
  ExecutionMode_MIN = ExecutionMode_ExecuteNow,
  ExecutionMode_MAX = ExecutionMode_Defensive
};

inline const ExecutionMode (&EnumValuesExecutionMode())[3] {
  static const ExecutionMode values[] = {
    ExecutionMode_ExecuteNow,
    ExecutionMode_Slice,
    ExecutionMode_Defensive
  };
  return values;
}

inline const char * const *EnumNamesExecutionMode() {
  static const char * const names[4] = {
    "ExecuteNow",
    "Slice",
    "Defensive",
    nullptr
  };
  return names;
}

inline const char *EnumNameExecutionMode(ExecutionMode e) {
  if (::flatbuffers::IsOutRange(e, ExecutionMode_ExecuteNow, ExecutionMode_Defensive)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesExecutionMode()[index];
}

enum LatencyRegime : int8_t {
  LatencyRegime_Nominal = 0,
  LatencyRegime_Medium = 1,
  LatencyRegime_Stressed = 2,
  LatencyRegime_MIN = LatencyRegime_Nominal,
  LatencyRegime_MAX = LatencyRegime_Stressed
};

inline const LatencyRegime (&EnumValuesLatencyRegime())[3] {
  static const LatencyRegime values[] = {
    LatencyRegime_Nominal,
    LatencyRegime_Medium,
    LatencyRegime_Stressed
  };
  return values;
}

inline const char * const *EnumNamesLatencyRegime() {
  static const char * const names[4] = {
    "Nominal",
    "Medium",
    "Stressed",
    nullptr
  };
  return names;
}

inline const char *EnumNameLatencyRegime(LatencyRegime e) {
  if (::flatbuffers::IsOutRange(e, LatencyRegime_Nominal, LatencyRegime_Stressed)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLatencyRegime()[index];
}

struct Quote FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef QuoteBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BID = 4,
    VT_ASK = 6
  };
  double bid() const {
    return GetField<double>(VT_BID, 0.0);
  }
  double ask() const {
    return GetField<double>(VT_ASK, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_BID, 8) &&
           VerifyField<double>(verifier, VT_ASK, 8) &&
           verifier.EndTable();
  }
};

struct QuoteBuilder {
  typedef Quote Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bid(double bid) {
    fbb_.AddElement<double>(Quote::VT_BID, bid, 0.0);
  }
  void add_ask(double ask) {
    fbb_.AddElement<double>(Quote::VT_ASK, ask, 0.0);
  }
  explicit QuoteBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Quote> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Quote>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Quote> CreateQuote(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    double bid = 0.0,
    double ask = 0.0) {
  QuoteBuilder builder_(_fbb);
  builder_.add_ask(ask);
  builder_.add_bid(bid);
  return builder_.Finish();
}

struct SimulationRequest FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SimulationRequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SIDE = 4,
    VT_SIZE_USD = 6,
    VT_LATENCY = 8,
    VT_MODE = 10,
    VT_CURRENT_QUOTE = 12,
    VT_INVENTORY_USD = 14
  };
  bool side() const {
    return GetField<uint8_t>(VT_SIDE, 0) != 0;
  }
  double size_usd() const {
    return GetField<double>(VT_SIZE_USD, 0.0);
  }
  ExecutionCoach::Sim::LatencyRegime latency() const {
    return static_cast<ExecutionCoach::Sim::LatencyRegime>(GetField<int8_t>(VT_LATENCY, 0));
  }
  ExecutionCoach::Sim::ExecutionMode mode() const {
    return static_cast<ExecutionCoach::Sim::ExecutionMode>(GetField<int8_t>(VT_MODE, 0));
  }
  const ExecutionCoach::Sim::Quote *current_quote() const {
    return GetPointer<const ExecutionCoach::Sim::Quote *>(VT_CURRENT_QUOTE);
  }
  double inventory_usd() const {
    return GetField<double>(VT_INVENTORY_USD, 0.0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SIDE, 1) &&
           VerifyField<double>(verifier, VT_SIZE_USD, 8) &&
           VerifyField<int8_t>(verifier, VT_LATENCY, 1) &&
           VerifyField<int8_t>(verifier, VT_MODE, 1) &&
           VerifyOffset(verifier, VT_CURRENT_QUOTE) &&
           verifier.VerifyTable(current_quote()) &&
           VerifyField<double>(verifier, VT_INVENTORY_USD, 8) &&
           verifier.EndTable();
  }
};

struct SimulationRequestBuilder {
  typedef SimulationRequest Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_side(bool side) {
    fbb_.AddElement<uint8_t>(SimulationRequest::VT_SIDE, static_cast<uint8_t>(side), 0);
  }
  void add_size_usd(double size_usd) {
    fbb_.AddElement<double>(SimulationRequest::VT_SIZE_USD, size_usd, 0.0);
  }
  void add_latency(ExecutionCoach::Sim::LatencyRegime latency) {
    fbb_.AddElement<int8_t>(SimulationRequest::VT_LATENCY, static_cast<int8_t>(latency), 0);
  }
  void add_mode(ExecutionCoach::Sim::ExecutionMode mode) {
    fbb_.AddElement<int8_t>(SimulationRequest::VT_MODE, static_cast<int8_t>(mode), 0);
  }
  void add_current_quote(::flatbuffers::Offset<ExecutionCoach::Sim::Quote> current_quote) {
    fbb_.AddOffset(SimulationRequest::VT_CURRENT_QUOTE, current_quote);
  }
  void add_inventory_usd(double inventory_usd) {
    fbb_.AddElement<double>(SimulationRequest::VT_INVENTORY_USD, inventory_usd, 0.0);
  }
  explicit SimulationRequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SimulationRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SimulationRequest>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SimulationRequest> CreateSimulationRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    bool side = false,
    double size_usd = 0.0,
    ExecutionCoach::Sim::LatencyRegime latency = ExecutionCoach::Sim::LatencyRegime_Nominal,
    ExecutionCoach::Sim::ExecutionMode mode = ExecutionCoach::Sim::ExecutionMode_ExecuteNow,
    ::flatbuffers::Offset<ExecutionCoach::Sim::Quote> current_quote = 0,
    double inventory_usd = 0.0) {
  SimulationRequestBuilder builder_(_fbb);
  builder_.add_inventory_usd(inventory_usd);
  builder_.add_size_usd(size_usd);
  builder_.add_current_quote(current_quote);
  builder_.add_mode(mode);
  builder_.add_latency(latency);
  builder_.add_side(side);
  return builder_.Finish();
}

inline const ExecutionCoach::Sim::SimulationRequest *GetSimulationRequest(const void *buf) {
  return ::flatbuffers::GetRoot<ExecutionCoach::Sim::SimulationRequest>(buf);
}

inline const ExecutionCoach::Sim::SimulationRequest *GetSizePrefixedSimulationRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<ExecutionCoach::Sim::SimulationRequest>(buf);
}

template <bool B = false>
inline bool VerifySimulationRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<ExecutionCoach::Sim::SimulationRequest>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedSimulationRequestBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<ExecutionCoach::Sim::SimulationRequest>(nullptr);
}

inline void FinishSimulationRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ExecutionCoach::Sim::SimulationRequest> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSimulationRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<ExecutionCoach::Sim::SimulationRequest> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Sim
}  // namespace ExecutionCoach

#endif  // FLATBUFFERS_GENERATED_SCHEMA_EXECUTIONCOACH_SIM_H_
