using System.Diagnostics;
using TradingEngineServer.Core.Models;

namespace TradingEngineServer.Core.Services;

/// <summary>
/// Result of a deterministic replay operation.
/// </summary>
public class ReplayResult
{
    public int EventsReplayed { get; set; }
    public int NewOrdersReplayed { get; set; }
    public int CancelsReplayed { get; set; }
    public int TradesGenerated { get; set; }
    public double ReplayTimeUs { get; set; }
    public OrderBookSnapshot? FinalSnapshot { get; set; }
}

/// <summary>
/// Deterministic Replay Engine. Given an ordered sequence of EngineEvents,
/// clears the order book and re-processes every event to rebuild full state.
/// This is equivalent to LMAX's event-sourcing pattern — the log IS the 
/// source of truth, and the order book is a derived projection.
/// </summary>
public class ReplayEngine
{
    /// <summary>
    /// Replays a list of events against a fresh order book, returning metrics.
    /// The order book is reset before replay begins to ensure determinism.
    /// </summary>
    public ReplayResult Replay(List<EngineEvent> events, IOrderBook orderBook)
    {
        var result = new ReplayResult();

        // Reset the book to a clean state
        orderBook.Reset();

        int tradeCount = 0;
        void CountTrade(Trade _) => tradeCount++;
        orderBook.OnTrade += CountTrade;

        var sw = Stopwatch.StartNew();

        foreach (var evt in events)
        {
            switch (evt.Type)
            {
                case EventType.NewOrder:
                    var order = new OrderCore(evt.OrderId, evt.OrderPrice, evt.OrderSize, evt.OrderIsBuy, evt.OrderUserId ?? string.Empty);
                    orderBook.AddOrder(in order);
                    result.NewOrdersReplayed++;
                    break;

                case EventType.CancelOrder:
                    orderBook.CancelOrder(evt.OrderId);
                    result.CancelsReplayed++;
                    break;

                case EventType.TradeExecution:
                    // Trade events are derived — they were generated by matching during 
                    // the original run. During replay, they'll be regenerated by the 
                    // matching engine when we replay the NewOrder events.
                    // We skip them here to avoid double-counting.
                    break;
            }
        }

        sw.Stop();

        orderBook.OnTrade -= CountTrade;

        result.EventsReplayed = events.Count;
        result.TradesGenerated = tradeCount;
        result.ReplayTimeUs = sw.Elapsed.TotalMicroseconds;
        result.FinalSnapshot = orderBook.GetSnapshot();

        return result;
    }
}
